### ISSUE TITLE
正常に動作する箇所としない個所がある

### ISSUE THREAD

**Issue by shiohara** [kawasima/sastruts-advanced-routes#1]
動作確認をしたところ、正常に動作する箇所としない個所がありました。
調査した結果、下記のような状況なのですが、どういった対処をとるべきでしょうか？

<pre>
・Actionクラスにメソッドが複数定義されているものは動作しない
  （1つだけ定義されているものは動作する）

   [原因]
    AdvancedRoutingFilterのdoFilter()メソッドでexecuteConfigを取得してフォワードさせているが、
    Actionクラスにメソッドが複数定義されている場合、executeConfigが取得できていない。
    
    executeConfigが取得できないのは取得する際、
    リクエストのパラメータに「SAStruts.method」キーが存在しないためと考えられる。

   参考（executeConfig取得ロジック）
        org.seasar.struts.config.S2ActionMappingのexecuteConfigsのサイズが1つの場合
        →1番目を取得
        org.seasar.struts.config.S2ActionMappingのexecuteConfigsのサイズが複数の場合
        →リクエストパラメータの「SAStruts.method」キーに指定されたメソッド名のexecuteConfigを取得

　 [対策]
    ・URLに何かしらの方法でパラメータを追加させる？
      例) /gakko/SCXXXX → /gakko/SCXXXX?SAStruts.method=top
</pre>

**Comment by kawasima** [comment]
どういう現象になるかをお願いします。
Actionにindexメソッドが無いことが原因な気がしますが…

**Comment by kawasima** [comment]
executeConfigの呼び出し方がちょっとおかしかったので修正しました。
masterをビルドして試してみてください。indexがないActionでもいけると思います。

**Comment by shiohara** [comment]
ご対応ありがとうございます。
再ビルドしたもので試しましたが、うまくいきませんでした。

現象についてですが、
単純に<match path="/a" to="sample#list">と定義しても、
SampleActionのlist()メソッドが呼ばれずに画面遷移しない(何も表示されない)といった状況です。

また、index()メソッドが無くても、メソッドが1つしか定義されていないものについては、
正常に動作しております。

**Comment by kawasima** [comment]
to の コントローラ名は大文字にしてみてください。

 &lt;match path="/a" to="Sample#list"/&gt;

のように。
サブパッケージがある場合は、次のように書きます。

 &lt;match path="/a" to="subpkg.Sample#list"/&gt;

**Comment by shiohara** [comment]
toのコントローラ名を大文字にしても結果は変わりませんでした。
（サブパッケージはありません。）

**Comment by kawasima** [comment]
すみません。pushが失敗してたみたいです。

kawasima/sastruts-advanced-routes@705ce8159c9a7b335a2f9f8347ee4271fda057b3

このバージョンでお願いします。

**Comment by shiohara** [comment]
ありがとうございます。
上記バージョンで<match path="/a" to="Sample#list"/>のような単純パターンは正常に動作しました。

ですが、以下のようなパターンはうまくいっておりません。
<match path="/a/:sampleId" to="Sample#detail"/>

「/a/001」というURLにアクセスした際に、
ActionFormのsampleIdに001が入るイメージですが、
この認識は正しいでしょうか？

**Comment by shiohara** [comment]
こちらで調査した結果を追記します。

<match path="/a/:sampleId" to="Sample#detail"/>
のパターンがうまくいっていなかった原因は、
以下のようにurlPatternを記述していたためでした。

<pre>
public class SampleAction {
    protected SampleForm form;
    
    \@Execute(validator = true, urlPattern = "detail/{sampleId}", input = "/error/validate")
    public String detail() {
        return "detail.vm"
    }
}
</pre>


urlPatternを"detail"に変更したところこのメソッドを呼ぶことはできました。
ですが、form.sampleIdには値が設定されていませんでした。
form.sampleIdに値を設定するためには何か特別なことをする必要があるのでしょうか？

**Comment by kawasima** [comment]
forwardのときにURLパスに入っているパラメータのセットが漏れていたので追加しました。

kawasima/sastruts-advanced-routes@99ab8934baac87667c9e52a3aee078fe62a36047

**Comment by shiohara** [comment]
ご対応ありがとうございます。

正常に動作することを確認しました。
