### ISSUE TITLE
namespaceの記述方法について

### ISSUE THREAD

**Issue by shiohara** [kawasima/sastruts-advanced-routes#10]
namespaceは以下のような使用ができると認識しているのですが、
想定する動作をしません。認識は合っていますでしょうか？

<pre>
&lt;namespace name="pre"&gt;
    &lt;match path="/sample/:sampleCd" to="Sample#index"/&gt;
&lt;/namespace&gt;

→ (想定) /pre/sample/01 {:controller ⇒ "pre/sample", :action ⇒ "index", :sampleCd="01"}
→ (現状) /sample/01 {:controller ⇒ "sample", :action ⇒ "index", :sampleCd="01"}
</pre>

また、以下のような使用やscopeの使用は可能でしょうか？

<pre>
&lt;namespace name="pre"&gt;
    &lt;root to="Index#index"/&gt;
    &lt;match path="/:controller/:action"/&gt;
&lt;/namespace&gt;

→ /pre/ {:controller ⇒ "pre/index", :action ⇒ "index"}
→ /pre/sample/list {:controller ⇒ "pre/sample", :action ⇒ "list"}
</pre>

<pre>
&lt;namespace name="pre1"&gt;
    &lt;namespace name="pre2"&gt;
        &lt;match path="/sample/:sampleCd" to="Sample#index"/&gt;   
    &lt;/namespace&gt;
&lt;/namespace&gt;

→ /pre1/pre2/sample/01 {:controller ⇒ "pre1/pre2/sample", :action ⇒ "index", :sampleCd="01"}
</pre>

**Comment by kawasima** [comment]
namespaceはきちんと実装できていなかったので対応しました。似たような機能で、scopeディレクティブを追加しているので、READMEをご確認ください。

namespaceのネストは対応していません。 

```
<namespace name="pre1/pre2">
    <match path="/sample/:sampleCd" to="Sample#index"/>
</namespace>
```

で、

```
/pre1/pre2/sample/01 {:controller => "pre1.pre2.Sample", :action => "index", :sampleCd => "01"}
```

は実現できます。

**Comment by shiohara** [comment]
ご対応ありがとうございます。
正しく動作することを確認しました。
