### ISSUE TITLE
Dynamic Segmentの境界について

### ISSUE THREAD

**Issue by growthfield** [kawasima/sastruts-advanced-routes#11]
routes.xmlの定義方法に関して質問させてください。
match要素のpath属性においてDynamic segmentとStatic segmentが混在するケースを扱いたいです。

例：にDynamic segmentであるhogeとfugaの間にStatic segmentであるandがある 

```
/:hogeand:fuga/
```

普通にそのままやると:hogeではなく:hogeandとして判定されます。
シェルで$10を${10}と書くように明確にDynamic segmentの境界を指定する方法はあるのでしょうか？

またそのような書き方が無いものかとテストケース用のroutes.xmlを確認したところ、括弧で境界を指定しているような定義がありましたがこれは境界ではなくOptional(任意)を意味しているのでしょうか？

以上よろしくお願いします。

**Comment by kawasima** [comment]
/(:hoge)and(:huga)/ でいけるように #2 で対応してます。

同時にrequirementでhogeやhugaの正規表現を書いて使ってください。

**Comment by growthfield** [comment]
了解です。
括弧についてですが、境界の明示以外にも任意マッチのセグメントという意味合いも合わせもっていますか？
(requiremtnsを併せて指定しないと任意になってしまうということでしょうか？)

**Comment by kawasima** [comment]
ちょっとここがRails3の仕様と異なるのかもしれませんが、:huga や :hoge などのDynamicSegmentを括弧で括っても任意の意味合いはもちません。
requirementsは単にマッチングを正確にするための補助的な位置づけです。

**Comment by growthfield** [comment]
ありがとうございます。了解しました。

Rails3のサンプル

/:controller(/:action(/:id))

みたいな表記を見かけたので任意になってしまうのかと勘違いしていました。

**Comment by growthfield** [comment]
クローズします。
