### ISSUE TITLE
urlForでURLを取得した際に最後の"/"がつかない

### ISSUE THREAD

**Issue by shiohara** [kawasima/sastruts-advanced-routes#13]
ルーティング定義を以下のようにしてもurlForでURLを取得した際に、
最後の"/"が付加されません。

&lt;match path="/sample/index/" to="Sample#index" /&gt;
→/sample/index

どのように最後の"/"を付加させればよいでしょうか？

**Comment by kawasima** [comment]
Railsでは一律末尾の"/"をとる仕様で、url_forのオプションでtrailing_slash => true を指定するとスラッシュがつくようになります。
これでははあまり使い勝手がよくないので、Advanced Routesではmatchのpathの最後のセグメントが"/"だったら、暗黙的にtrailing_slash => trueの動作にしようと思います。

**Comment by shiohara** [comment]
最新のバージョンで正常に動作することを確認しました。
ご対応ありがとうございました。
