### ISSUE TITLE
クラスパスが同じ場合のurlForの動作について

### ISSUE THREAD

**Issue by shiohara** [kawasima/sastruts-advanced-routes#14]
以下のようにクラスパスが同じ場合、
パラメータの有無によってurlを区別できる認識でしたが、
現状、区別されていません。

この認識は間違っていますでしょうか？
間違っている場合、
これらのurlを区別することは可能でしょうか？

<pre>
&lt;match path="/sample/abc_(:abcCd)/def_(:defCd)/ghi_(ghiCd)/" to="Sample#list"&gt;
    &lt;requirements&gt;
        &lt;requirement name="abcCd" value="\w+"/&gt;
        &lt;requirement name="defCd" value="\w+"/&gt;
        &lt;requirement name="ghiCd" value="\w+"/&gt;
    &lt;/requirements&gt;
&lt;/match&gt;
&lt;match path="/sample/abc_(:abcCd)/def_(:defCd)/" to="Sample#list"&gt;
    &lt;requirements&gt;
        &lt;requirement name="abcCd" value="\w+"/&gt;
        &lt;requirement name="defCd" value="\w+"/&gt;
    &lt;/requirements&gt;
&lt;/match&gt;
&lt;match path="/sample/abc_(:abcCd)/" to="Sample#list"&gt;
    &lt;requirements&gt;
        &lt;requirement name="abcCd" value="\w+"/&gt;
    &lt;/requirements&gt;
&lt;/match&gt;
&lt;match path="/sample/list" to="Sample#list"/&gt;

urlFor("Sample#list?abcCd=XXXX")
（現状）
→/sample/abc_XXXX/def_/ghi_/
（期待する値）
→/sample/abc_XXXX/
</pre>

**Comment by kawasima** [comment]
#12 と同じ話だと思うのですが、handle-contextpathブランチの最新で動作しているか再確認してみてください。

**Comment by shiohara** [comment]
#12と同じ内容でした。申し訳ありません。
handle-contextpathブランチの最新で動作しているか確認し、クローズします。

**Comment by shiohara** [comment]
正常に動作していることを確認しました。
