### ISSUE TITLE
urlForの仕様確認

### ISSUE THREAD

**Issue by shiohara** [kawasima/sastruts-advanced-routes#16]
rootタグで定義したクラスパスをurlForに渡すと、
「//」が返ってきます。
これは仕様通りでしょうか？

<pre>
&lt;root to="Index#index"/&gt;

UrlRewriter.urlFor("Index#index")
→ //
</pre>

**Comment by kawasima** [comment]
単純なバグだったので修正しました。
なお、handle-contextpathブランチは役目を終えたので、masterにマージしています。この修正もmasterに対して実施しています。
ブランチを切り替えて使ってください。

**Comment by shiohara** [comment]
ご対応ありがとうございました。
masterのもので確認いたします。
