### ISSUE TITLE
階層の一部をパラメータとして扱う場合について

### ISSUE THREAD

**Issue by shiohara** [kawasima/sastruts-advanced-routes#2]
階層の一部をパラメータとして扱うために、
以下のように記述したのですが、マッチングされません。
どのように記述すればよいのでしょうか？

<pre>
&lt;match path="/sample_:sampleCd/detail" to="Sample#detail"&gt;
</pre>

というルーティングで、/sample_001/detailのようなURLに対応させたいです。

**Comment by kawasima** [comment]
Rails2のルーティングの仕様では多分途中マッチング出来ないと思うのですが、Rails3 の記法では可能なので、その機能を実装しました。

03fdb648418dd58415e9fc1bdaddba4e7d387fdf

```
<match path="/sample_(:sampleCd)/detail" to="Sample#detail">
    <requirements>
        <requirement name="sampleCd" value="\d+"/>
    </requirements>
</match>
```

のようにダイナミックセグメントを括弧で囲い、requirementsを定義してください。

**Comment by shiohara** [comment]
ご対応ありがとうございます。

最新のソースで動作確認できました。
