### ISSUE TITLE
OptimizedRecognizerでDynamic Segmentを正しく扱えずNoRouteExceptionが発生するケースがある

### ISSUE THREAD

**Issue by growthfield** [kawasima/sastruts-advanced-routes#25]
OptimizedRecognizerでDynamic Segmentを正しく扱えずNoRouteExceptionが発生するケースがあります。
再現方法は以下です。

```
<match path=":greeting/:name" to="DynamicGreet#index">
  <requirements>
    <requirement name="greeting" value="hello" />
  </requirements>
</match>
<match path="hello" to="StaticGreet#index">
</match>
```

上記の2つのmatch定義をしたroutes.xmlに対して以下UnitTestのアサーションが失敗します。

```
assertGenerates("/hello/world", "DynamicGreet#index?greeting=hello&name=world");
assertRecognizes("DynamicGreet#index?greeting=hello&name=world", "/hello/world");
```

※assertGeneratesは成功しますが、後者のassertRecognizesでNoRouteExceptionが発生します。

コードを追ってみたところ、
OptimizedRecognizer内にてDynamic segmentから始まる":greeting/:name"のルート探索時にStatic segmentである"hello"にマッチしてしまい誤った探索ルートに入りルートが見つからない状態になっているようです。

OptimizedRecognizer#optimize(45,46行目)のルートを効率的に検索するためのインデックスツリーを構築する際の処理が気になっています。

```
if (StringUtil.isNotEmpty(seg) && seg.charAt(0) == '?') {
    seg = ":dynamic";
}
```

`seg.charAt(0) == '?'`のケースが分からなかったのですが、
`seg.charAt(0) == ':'`とすることで想定通りの動きになりそうな気がします。

**Comment by kawasima** [comment]
Railsのここのコードなのですが…

https://github.com/rails/rails/blob/2-3-stable/actionpack/lib/action_controller/routing/recognition_optimisation.rb#L81

完全に'?'と':'を取り違えてますね…
仰るとおり、seg.charAt(0) == ':' が正しいです。
