### ISSUE TITLE
デフォルトのルーティングについて

### ISSUE THREAD

**Issue by shiohara** [kawasima/sastruts-advanced-routes#4]
デフォルトのルーティング(&lt;match path="/:controller/:action"/&gt;)についてですが、
ホットデプロイではない場合、ComponentControllerDetectorクラスのdetect()で
コントローラをすべて取得できないため、正常に動作しません。
（取得できるコントローラはサーバー起動後の初回アクセス時のコントローラとrootで設定したコントローラのみです。）

すべてのコントローラを取得するためには、何か設定等が必要でしょうか？

**Comment by kawasima** [comment]
現象からすると、もしかしてWarmDeployで動かしてますか?
確かにWarmDeployだと、ComponentControllerDetectorでは動かないので、Detectorの判定ロジックを修正します。

**Comment by shiohara** [comment]
WarmDeployで動かしていました。
