### ISSUE TITLE
urlForの仕様確認

### ISSUE THREAD

**Issue by shiohara** [kawasima/sastruts-advanced-routes#5]
urlForを用いてURLを作成した場合、
クエリストリングを付加させることはできないのでしょうか？

例）
urlFor("admin.User#index?sampleNo=2")
                        ↓
/user/list?sampleNo=2

**Comment by kawasima** [comment]
すみません。未実装でした。
パスマッチしないパラメータはクエリストリングとして付け足されるように修正します。

**Comment by shiohara** [comment]
ご対応ありがとうございます。
クエリストリングが付加されることを確認しました。
